name: Raspberry Pi compile
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: raspi_3_bullseye:20230102
          commands: |
            # Rust complains (rightly) that $HOME doesn't match eid home
            export HOME=/root
            # Workaround to CI worker being stuck on Updating crates.io index
            export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
            # Install setup prerequisites
            sudo apt-get update -y --allow-releaseinfo-change
            sudo apt-get upgrade -y
            sudo apt-get autoremove -y
            sudo apt-get install curl
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
            . "$HOME/.cargo/env"
            sudo apt install -y nodejs npm
            # Install build tools and tauri-cli requirements
            sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
            cargo install tauri-cli
            # Install frontend dependencies
            npm install
            # Build the application
            cargo tauri build
      - name: Upload deb bundle
        uses: actions/upload-artifact@v3
        with:
          name: Debian Bundle
          path: ${{ github.workspace }}/target/release/bundle/deb/neyaden-app_0.1.0_arm64.deb
